"""Task 2 -- immutable, hashable ledger records.

A ``Transaction`` is a fact that happened. Once created it never changes, which
is why it is frozen and hashable: you can put transactions in a ``set`` to
de-duplicate a replayed batch.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from minibank.exceptions import InvalidAmountError
from minibank.money import Money


class TransactionType(enum.Enum):
    """The kinds of ledger entry this system can produce.

    Already complete -- use these members, do not invent new strings.
    """

    DEPOSIT = "DEPOSIT"
    WITHDRAWAL = "WITHDRAWAL"
    TRANSFER_IN = "TRANSFER_IN"
    TRANSFER_OUT = "TRANSFER_OUT"
    INTEREST = "INTEREST"
    FEE = "FEE"

    @property
    def is_credit(self) -> bool:
        """True for entries that increase the balance."""
        return self in {
            TransactionType.DEPOSIT,
            TransactionType.TRANSFER_IN,
            TransactionType.INTEREST,
        }

    def __str__(self) -> str:  # pragma: no cover - cosmetic
        return self.value


def _utc_now() -> datetime:
    """Timezone-aware 'now'. Naive datetimes are a bug in financial records."""
    return datetime.now(timezone.utc)


@dataclass(frozen=True)
class Transaction:
    """One immutable line in an account ledger.

    Fields
    ------
    txn_id:
        Unique id. Generated by the account, not by the caller.
    type:
        A ``TransactionType`` member.
    amount:
        Always a POSITIVE ``Money``. Direction is carried by ``type``, not by
        the sign -- this is the convention the tests assume.
    balance_after:
        The account balance once this entry was applied. Makes the ledger
        auditable without replaying it.
    description:
        Free text, may be empty.
    timestamp:
        Defaults to ``_utc_now()``.

    Examples
    --------
    >>> t = Transaction("T1", TransactionType.DEPOSIT, Money("100"), Money("100"))
    >>> t.signed_amount
    Money('100.00', 'INR')
    >>> hash(t) == hash(t)
    True
    """

    txn_id: str
    type: TransactionType
    amount: Money
    balance_after: Money
    description: str = ""
    timestamp: datetime = field(default_factory=_utc_now)

    def __post_init__(self) -> None:
        """Validate the record.

        * ``amount`` must be a ``Money`` and must NOT be negative
          -> ``InvalidAmountError``.
        * ``type`` must be a ``TransactionType`` member -> ``InvalidAmountError``.
        """
        if not isinstance(self.amount, Money) or not self.amount.is_positive:
            raise InvalidAmountError(self.amount, "transaction amount must be positive Money")
        if not isinstance(self.type, TransactionType):
            raise InvalidAmountError(self.type, "invalid transaction type")

    @property
    def signed_amount(self) -> Money:
        """``+amount`` for credits, ``-amount`` for debits.

        Use ``self.type.is_credit``. This is what a statement print-out wants.
        """
        return self.amount if self.type.is_credit else -self.amount

    def __hash__(self) -> int:
        """MANDATORY. Hash on ``txn_id`` alone -- the id identifies the record."""
        return hash(self.txn_id)

    def __eq__(self, other: object) -> bool:
        """Two transactions are equal iff their ``txn_id`` matches.
        Non-Transaction -> ``NotImplemented``."""
        if not isinstance(other, Transaction):
            return NotImplemented
        return self.txn_id == other.txn_id

    def __repr__(self) -> str:
        """MANDATORY. e.g. ``Transaction(T1, DEPOSIT, INR 100.00)``."""
        return f"Transaction({self.txn_id}, {self.type.name}, {self.amount})"

    def to_dict(self) -> dict:
        """JSON-ready dict.

        Required exact keys::

            {"txn_id": str, "type": str, "amount": str, "currency": str,
             "balance_after": str, "description": str, "timestamp": str}

        ``amount`` / ``balance_after`` are the plain decimal strings
        ("100.00"), and ``timestamp`` is ``datetime.isoformat()``.
        """
        return {
            "txn_id": self.txn_id,
            "type": self.type.value,
            "amount": str(self.amount.amount),
            "currency": self.amount.currency,
            "balance_after": str(self.balance_after.amount),
            "description": self.description,
            "timestamp": self.timestamp.isoformat(),
        }
